# --------------------------------------------------------------------------
# Name and model type
# --------------------------------------------------------------------------
name: MACADKD_EDSR_x2
model_type: MCADKD        # Adaptive Contrastive–Adversarial KD
scale: 2
num_gpu: auto
manual_seed: 10

# --------------------------------------------------------------------------
# Datasets
# --------------------------------------------------------------------------
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /path/to/DIV2K_train_HR  # Update this path
    dataroot_lq: /path/to/DIV2K_train_LR_bicubic/X2  # Update this path
    filename_tmpl: '{}x2'
    io_backend:
      type: disk
    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 32 # because of InfoNCE Loss
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /path/to/benchmark/Set5/HR  # Update this path
    dataroot_lq: /path/to/benchmark/Set5/LR_bicubic/X2  # Update this path
    filename_tmpl: '{}x2'
    io_backend:
      type: disk
  val_2:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: /home/sean/ACCV/data/benchmark/Urban100/HR
    dataroot_lq: /home/sean/ACCV/data/benchmark/Urban100/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk
  # val_4:
  #   name: DIV2K_Val
  #   type: PairedImageDataset
  #   dataroot_gt: /home/sean/SR_project/ACCV/data/DF2K/DIV2K_valid_HR
  #   dataroot_lq: /home/sean/SR_project/ACCV/data/DF2K/DIV2K_valid_LR_bicubic/X2
  #   filename_tmpl: '{}x2'
  #   io_backend:
  #     type: disk


  # … other val splits as before …

# --------------------------------------------------------------------------
# Network structures
# --------------------------------------------------------------------------

# network structures
network_g:
  type: EDSR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 32
  upscale: 2
  res_scale: 0.1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]


network_t:
  type: EDSR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 256
  num_block: 32
  upscale: 2
  res_scale: 0.1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]

# Small SR-GAN discriminator
discriminator:
  # type: DiscriminatorVGG
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  # input_size: 128
  # input_size: 96

# --------------------------------------------------------------------------
# Paths
# --------------------------------------------------------------------------
path:
  pretrain_network_g: ~ 
  pretrain_network_t: /path/to/edsr_teacher_checkpoint.pth  # Update with teacher model path
  strict_load_g: false
  resume_state: ~

# --------------------------------------------------------------------------
# Training settings
# --------------------------------------------------------------------------
train:
  # if no optim_t, teacher is automatically not backproped and weights are not updated

  # Optimizer for EDSR + proj head + τ (already defined by BaseKD)
  optim_g:
    type: Adam
    lr: !!float 1e-3
    betas: [0.9, 0.99]
    weight_decay: 0

  # Optimizer for discriminator
  optim_d:
    type: Adam
    lr: !!float 1e-3
    betas: [0.9, 0.99]
    weight_decay: 0

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1

  # ========================================================================
  # ACAKD losses (now as *_opt) DRAGON1 Server
  # ========================================================================
  pixel_opt:
    type: L1Loss
    loss_weight: 3.0
    reduction: mean
    
  resp_kd_opt:
    type: L1Loss
    loss_weight: 0.5
    reduction: mean

  contrastive_opt:
    type: hybrid          # Use both image and patch level
    patch_size: 48        # Good balance for 2x SR (adjust for your scale)
    num_patches: 8        # Start with 8, can increase if memory allows
    image_weight: 0.3     # Lower weight for image-level
    patch_weight: 0.7     # Higher weight for patch-level
    loss_weight: 0.05     # Increase from your current 0.01

  adversarial_opt:
    type: GANLoss
    gan_type: vanilla
    loss_weight: 0.01

# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------
val:
  val_freq: 5000.0
  save_img: false
  self_ensemble: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 2
      test_y_channel: true

# --------------------------------------------------------------------------
# Logging
# --------------------------------------------------------------------------
logger:
  print_freq: 100
  save_checkpoint_freq: 5000.0
  use_tb_logger: true
  wandb:
    project: ~

# --------------------------------------------------------------------------
# Distributed
# --------------------------------------------------------------------------
dist_params:
  backend: nccl
  port: 29500
